<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="ECDSA\新文件夹\**" />
    <EmbeddedResource Remove="ECDSA\新文件夹\**" />
    <None Remove="ECDSA\新文件夹\**" />
    <Page Remove="ECDSA\新文件夹\**" />
  </ItemGroup>

</Project>
